baseURL = 'https://b0x68.github.io/'
languageCode = 'en-us'
title = 'b0x68'
theme = 'hugo-book'
BookMenuBundle = 'content/menu'

[services]
  [services.googleAnalytics]
    id = 'G-JZB9YT32PY'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'
